import { createClient } from "@/utils/supabase/server";
import Link from "next/link";
import { FiChevronLeft, FiChevronRight, FiPackage } from "react-icons/fi";
import { LabelDownloadButton } from "@/components/admin/LabelDownloadButton";
import { COURIER_LABEL, type CourierType } from "@/utils/admin/labels/courier";

export const dynamic = "force-dynamic";

export default async function AdminShipmentsPage({
  searchParams,
}: {
  searchParams: Promise<{ page?: string }>;
}) {
  const resolvedSearchParams = await searchParams;
  const currentPage = parseInt(resolvedSearchParams.page || "1", 10);
  const itemsPerPage = 10;
  const offset = (currentPage - 1) * itemsPerPage;

  const supabase = await createClient();

  const { data: shipments, count, error } = await supabase
    .from("shipments")
    .select("*, orders(*), users!shipments_created_by_fkey(full_name)", { count: "exact" })
    .order("created_at", { ascending: false })
    .range(offset, offset + itemsPerPage - 1);

  if (error) {
    console.error("Error fetching shipments:", error);
  }

  const totalPages = count ? Math.ceil(count / itemsPerPage) : 1;

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-3xl font-bold tracking-tight text-slate-900">Shipments</h1>
        <p className="text-slate-500 mt-1">Manage generated shipping labels and dispatch history.</p>
      </div>

      <div className="bg-white rounded-xl shadow-sm border border-slate-200 overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full text-left text-sm text-slate-600">
            <thead className="bg-slate-50 text-slate-900 font-semibold border-b border-slate-200">
              <tr>
                <th className="px-6 py-4">Order #</th>
                <th className="px-6 py-4">Courier</th>
                <th className="px-6 py-4">AWB / Tracking</th>
                <th className="px-6 py-4">Dispatch Date</th>
                <th className="px-6 py-4">Generated By</th>
                <th className="px-6 py-4 text-right">Label</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-200">
              {shipments?.map((s) => (
                <tr key={s.id} className="hover:bg-slate-50 transition-colors">
                  <td className="px-6 py-4">
                    <Link
                      href={`/admin/orders`}
                      className="font-mono text-xs font-semibold text-emerald-600 hover:underline flex items-center gap-2"
                    >
                      <FiPackage className="text-emerald-500" />
                      {s.orders?.id?.split("-")[0] ?? "—"}
                    </Link>
                  </td>
                  <td className="px-6 py-4">
                    <span className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-blue-100 text-blue-800">
                      {COURIER_LABEL[s.courier as CourierType] || s.courier}
                    </span>
                  </td>
                  <td className="px-6 py-4 font-mono text-xs text-slate-700">
                    {s.awb ?? "—"}
                  </td>
                  <td className="px-6 py-4">
                    {s.dispatch_date ? new Date(s.dispatch_date).toLocaleDateString() : "—"}
                  </td>
                  <td className="px-6 py-4">
                    {s.users?.full_name ?? "—"}
                  </td>
                  <td className="px-6 py-4 text-right">
                    <LabelDownloadButton
                      shipmentId={s.id}
                      hasLabel={!!s.label_pdf_url}
                    />
                  </td>
                </tr>
              ))}
              {(!shipments || shipments.length === 0) && (
                <tr>
                  <td colSpan={6} className="px-6 py-8 text-center text-slate-500">
                    No shipments or labels generated yet.
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>

        {totalPages > 1 && (
          <div className="border-t border-slate-200 px-6 py-4 flex items-center justify-between">
            <span className="text-sm text-slate-500">
              Showing {Math.min(offset + 1, count || 0)} to {Math.min(offset + itemsPerPage, count || 0)} of {count} entries
            </span>
            <div className="flex items-center gap-2">
              <Link
                href={`/admin/shipments?page=${Math.max(1, currentPage - 1)}`}
                className={`p-2 rounded border ${
                  currentPage === 1
                    ? "border-slate-200 text-slate-300 pointer-events-none"
                    : "border-slate-300 text-slate-600 hover:bg-slate-50"
                }`}
              >
                <FiChevronLeft />
              </Link>
              <Link
                href={`/admin/shipments?page=${Math.min(totalPages, currentPage + 1)}`}
                className={`p-2 rounded border ${
                  currentPage === totalPages
                    ? "border-slate-200 text-slate-300 pointer-events-none"
                    : "border-slate-300 text-slate-600 hover:bg-slate-50"
                }`}
              >
                <FiChevronRight />
              </Link>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
